default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy-pixi
        name: mypy (pixi dev)
        language: system
        entry: pixi run -e dev mypy --config-file=pyproject.toml app tests
        types: [python]
        stages: [pre-push]
        pass_filenames: false  # faster + cache works better

  - repo: local
    hooks:
      - id: django-check-pixi
        name: Django Check (pixi dev)
        language: system
        entry: pixi run -e dev django:manage check --fail-level=ERROR
        pass_filenames: false
        stages: [pre-push]

      - id: pytest-unit-pixi
        name: Run Unit Tests (pixi dev)
        language: system
        entry: pixi run -e dev pytest tests/unit/ -v --tb=short
        pass_filenames: false
        stages: [pre-push]
        require_serial: true
