name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: spatialite://./app/test-db.sqlite
      DJANGO_SECRET_KEY: "test-secret-key-min-30-characters-long-for-ci"
      ENVIRONMENT: "test"
      ODM_CONTAINER_URL: "test_odm_url"
      ODM_CONTAINER_VOLUME: "test_odm_volume"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.49.0
          cache: true

      - name: Install Pixi environment
        run: pixi install -e test

      - name: Format code with Ruff
        run: pixi run -e test code-quality:format

      - name: Lint with Ruff
        run: pixi run -e test code-quality:lint

      - name: Run Unit, Integration, and E2E Tests
        run: pixi run -e test test
